gray_moderacion_home:
    path: /mod/home
    defaults: { _controller: gray.moderacion.controller:home }

gray_moderacion_create:
    path: /mod/create
    defaults: { _controller: gray.moderacion.controller:handle }

gray_moderacion_store:
    path: /mod/store/{tipo_revision}
    defaults: { _controller: gray.moderacion.controller:insert_revision }

gray_moderacion_view:
    path: /mod/view/{user_id}
    defaults: { _controller: gray.moderacion.controller:view_user }

gray_moderacion_view_mod:
    path: /mod/viewMod/{user_id}
    defaults: { _controller: gray.moderacion.controller:view_mod }

gray_moderacion_view_rev:
    path: /mod/viewRev/{rev_id}
    defaults: { _controller: gray.moderacion.controller:view_rev }

gray_moderacion_view_admin:
    path: /mod/viewAdmin
    defaults: { _controller: gray.moderacion.controller:view_admin }

gray_moderacion_view_admin_all:
    path: /mod/viewAdminAll
    defaults: { _controller: gray.moderacion.controller:view_admin_all }

gray_moderacion_view_puntuaciones_all:
    path: /mod/viewPuntuacionesAll
    defaults: { _controller: gray.moderacion.controller:view_puntuaciones_all }

gray_moderacion_view_recompensas_rev:
    path: /mod/viewRecompensaRev/{rev_id}
    defaults: { _controller: gray.moderacion.controller:view_recompensa_rev }

gray_moderacion_dar_recompensa_tema:
    path: /mod/dar_recompensa_tema
    defaults: { _controller: gray.moderacion.controller:dar_recompensa }

gray_moderacion_dar_recompensa_mision:
    path: /mod/dar_recompensa_mision
    defaults: { _controller: gray.moderacion.controller:dar_recompensa_mision }

gray_moderacion_dar_recompensa_combate:
    path: /mod/dar_recompensa_combate
    defaults: { _controller: gray.moderacion.controller:dar_recompensa_combate }

gray_moderacion_update_revision:
    path: /mod/update_revision
    defaults: { _controller: gray.moderacion.controller:update_revision }

gray_moderacion_revisione_user:
    path: /moderaciones/revisiones_user
    defaults: { _controller: gray.moderacion.controller:get_revisiones_user }

gray_moderacion_revisione_mod:
    path: /moderaciones/revisiones_mod
    defaults: { _controller: gray.moderacion.controller:get_revisiones_mod }

gray_moderacion_revision_vista:
    path: /moderaciones/revision_vista
    defaults: { _controller: gray.moderacion.controller:get_revision_vista }

gray_moderacion_get_moderadores:
    path: /moderaciones/moderadores
    defaults: { _controller: gray.moderacion.controller:get_revisiones_no_asignadas }

gray_moderacion_get_moderadores_all:
    path: /moderaciones/moderadores_all
    defaults: { _controller: gray.moderacion.controller:get_revisiones_asignadas }

gray_moderacion_get_puntuaciones_all:
    path: /moderaciones/puntuaciones_all
    defaults: { _controller: gray.moderacion.controller:get_puntuaciones_mod }

gray_moderacion_get_recompensa_rev:
    path: /moderaciones/recompensa_rev
    defaults: { _controller: gray.moderacion.controller:get_recompensas_rev }

gray_moderacion_participantes:
    path: /moderacion/participantes
    defaults: { _controller: gray.moderacion.controller:get_participantes }

gray_moderacion_recompensa_tema:
    path: /mod/recompensa_tema/{rev_id}
    defaults: { _controller: gray.moderacion.controller:get_vista_recompensa_tema }

gray_moderacion_recompensa_mision:
    path: /mod/recompensa_mision/{rev_id}
    defaults: { _controller: gray.moderacion.controller:get_vista_recompensa_mision }

gray_moderacion_recompensa_combate:
    path: /mod/recompensa_combate/{rev_id}
    defaults: { _controller: gray.moderacion.controller:get_vista_recompensa_combate }

gray_moderacion_asignar:
    path: /admin/asignar/{revision_id}
    defaults: { _controller: gray.moderacion.controller:update_revision_mod }
