gray_moderacion_home:
    path: /mod
    defaults: { _controller: gray.moderacion.controller:handle }

gray_moderacion_store:
    path: /mod/store/{tipo_revision}
    defaults: { _controller: gray.moderacion.controller:insert_revision }

gray_moderacion_view:
    path: /mod/view/{user_id}
    defaults: { _controller: gray.moderacion.controller:view_user }

gray_moderacion_view_mod:
    path: /mod/viewMod/{user_id}
    defaults: { _controller: gray.moderacion.controller:view_mod }

gray_moderacion_view_rev:
    path: /mod/viewRev/{rev_id}
    defaults: { _controller: gray.moderacion.controller:view_rev }

gray_moderacion_view_admin:
    path: /mod/viewAdmin
    defaults: { _controller: gray.moderacion.controller:view_admin }

gray_moderacion_revisione_user:
    path: /moderaciones/revisiones_user
    defaults: { _controller: gray.moderacion.controller:get_revisiones_user }

gray_moderacion_revisione_mod:
    path: /moderaciones/revisiones_mod
    defaults: { _controller: gray.moderacion.controller:get_revisiones_mod }

gray_moderacion_revision_vista:
    path: /moderaciones/revision_vista
    defaults: { _controller: gray.moderacion.controller:get_revision_vista }

gray_moderacion_get_moderadores:
    path: /moderaciones/moderadores
    defaults: { _controller: gray.moderacion.controller:get_revisiones_no_asignadas }

gray_moderacion_participantes:
    path: /moderacion/participantes
    defaults: { _controller: gray.moderacion.controller:get_participantes }

gray_moderacion_recompensa_usuario:
    path: /mod/recompensa_usuario/{rev_id}
    defaults: { _controller: gray.moderacion.controller:get_vista_recompensa }

gray_moderacion_dar_recompensa_usuario:
    path: /mod/otorga_recompensa/
    defaults: { _controller: gray.moderacion.controller:insert_recompensa }

gray_moderacion_asignar:
    path: /admin/asignar/{revision_id}
    defaults: { _controller: gray.moderacion.controller:update_revision_mod }
