services:
    gray.moderacion.controller:
        class: gray\moderacion\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
