akira_sladmin_home:
    path: /sladmin/home
    defaults: { _controller: akira.sladmin.controller:handle }
    
akira_sladmin_aldeas:
    path: /sladmin/aldeas
    defaults: { _controller: akira.sladmin.controller:aldeas_view }
    
akira_sladmin_aldeas_ins:
    path: /sladmin/aldeas/ins
    defaults: { _controller: akira.sladmin.controller:aldeas_ins }
    
akira_sladmin_aldeas_upd:
    path: /sladmin/aldeas/upd/{aldea_id}
    defaults: { _controller: akira.sladmin.controller:aldeas_upd }
    
akira_sladmin_aldeas_del:
    path: /sladmin/aldeas/del/{aldea_id}
    defaults: { _controller: akira.sladmin.controller:aldeas_del }
    
    
akira_sladmin_niveles:
    path: /sladmin/niveles
    defaults: { _controller: akira.sladmin.controller:niveles_view }
    
akira_sladmin_niveles_ins:
    path: /sladmin/niveles/ins
    defaults: { _controller: akira.sladmin.controller:niveles_ins }
    
akira_sladmin_niveles_upd:
    path: /sladmin/niveles/upd/{nivel}
    defaults: { _controller: akira.sladmin.controller:niveles_upd }
    
akira_sladmin_niveles_del:
    path: /sladmin/niveles/del/{nivel}
    defaults: { _controller: akira.sladmin.controller:niveles_del }
    
    
akira_sladmin_ramas:
    path: /sladmin/ramas
    defaults: { _controller: akira.sladmin.controller:ramas_view }
    
akira_sladmin_ramas_ins:
    path: /sladmin/ramas/ins
    defaults: { _controller: akira.sladmin.controller:ramas_ins }
    
akira_sladmin_ramas_upd:
    path: /sladmin/ramas/upd/{rama_id}
    defaults: { _controller: akira.sladmin.controller:ramas_upd }
    
akira_sladmin_ramas_del:
    path: /sladmin/ramas/del/{rama_id}
    defaults: { _controller: akira.sladmin.controller:ramas_del }
    
    
akira_sladmin_tecnicas:
    path: /sladmin/tecnicas
    defaults: { _controller: akira.sladmin.controller:tecnicas_view }
    
akira_sladmin_tecnicas_ins:
    path: /sladmin/tecnicas/ins
    defaults: { _controller: akira.sladmin.controller:tecnicas_ins }
    
akira_sladmin_tecnicas_upd:
    path: /sladmin/tecnicas/upd/{tecnica_id}
    defaults: { _controller: akira.sladmin.controller:tecnicas_upd }
    
akira_sladmin_tecnicas_del:
    path: /sladmin/tecnicas/del/{tecnica_id}
    defaults: { _controller: akira.sladmin.controller:tecnicas_del }
    
    
akira_sladmin_arquetipos:
    path: /sladmin/arquetipos
    defaults: { _controller: akira.sladmin.controller:arquetipos_view }
    
akira_sladmin_arquetipos_ins:
    path: /sladmin/arquetipos/ins
    defaults: { _controller: akira.sladmin.controller:arquetipos_ins }
    
akira_sladmin_arquetipos_upd:
    path: /sladmin/arquetipos/upd/{arquetipo_id}
    defaults: { _controller: akira.sladmin.controller:arquetipos_upd }
    
akira_sladmin_arquetipos_del:
    path: /sladmin/arquetipos/del/{arquetipo_id}
    defaults: { _controller: akira.sladmin.controller:arquetipos_del }
    
    
akira_sladmin_habilidades:
    path: /sladmin/habilidades
    defaults: { _controller: akira.sladmin.controller:habilidades_view }
    
akira_sladmin_habilidades_ins:
    path: /sladmin/habilidades/ins
    defaults: { _controller: akira.sladmin.controller:habilidades_ins }
    
akira_sladmin_habilidades_upd:
    path: /sladmin/habilidades/upd/{habilidad_id}
    defaults: { _controller: akira.sladmin.controller:habilidades_upd }
    
akira_sladmin_habilidades_del:
    path: /sladmin/habilidades/del/{habilidad_id}
    defaults: { _controller: akira.sladmin.controller:habilidades_del }
    
    
akira_sladmin_tiendas:
    path: /sladmin/tiendas
    defaults: { _controller: akira.sladmin.controller:tiendas_view }
    
akira_sladmin_tiendas_ins:
    path: /sladmin/tiendas/ins
    defaults: { _controller: akira.sladmin.controller:tiendas_ins }
    
akira_sladmin_tiendas_upd:
    path: /sladmin/tiendas/upd/{shop_id}
    defaults: { _controller: akira.sladmin.controller:tiendas_upd }
    
akira_sladmin_tiendas_del:
    path: /sladmin/tiendas/del/{shop_id}
    defaults: { _controller: akira.sladmin.controller:tiendas_del }
    
    
akira_sladmin_items:
    path: /sladmin/items
    defaults: { _controller: akira.sladmin.controller:items_view }
    
akira_sladmin_items_ins:
    path: /sladmin/items/ins
    defaults: { _controller: akira.sladmin.controller:items_ins }
    
akira_sladmin_items_upd:
    path: /sladmin/items/upd/{item_id}
    defaults: { _controller: akira.sladmin.controller:items_upd }
    
akira_sladmin_items_del:
    path: /sladmin/items/del/{item_id}
    defaults: { _controller: akira.sladmin.controller:items_del }
    
    
akira_sladmin_invocaciones:
    path: /sladmin/invocaciones
    defaults: { _controller: akira.sladmin.controller:invocaciones_view }
    
akira_sladmin_invocaciones_ins:
    path: /sladmin/invocaciones/ins
    defaults: { _controller: akira.sladmin.controller:invocaciones_ins }
    
akira_sladmin_invocaciones_upd:
    path: /sladmin/invocaciones/upd/{invocacion_id}
    defaults: { _controller: akira.sladmin.controller:invocaciones_upd }
    
akira_sladmin_invocaciones_del:
    path: /sladmin/invocaciones/del/{invocacion_id}
    defaults: { _controller: akira.sladmin.controller:invocaciones_del }
    
    
akira_sladmin_cofres:
    path: /sladmin/cofres
    defaults: { _controller: akira.sladmin.controller:cofres_view }
    
akira_sladmin_cofres_ins:
    path: /sladmin/cofres/ins
    defaults: { _controller: akira.sladmin.controller:cofres_ins }
    
akira_sladmin_cofres_upd:
    path: /sladmin/cofres/upd/{recompensa_id}
    defaults: { _controller: akira.sladmin.controller:cofres_upd }
    
akira_sladmin_cofres_del:
    path: /sladmin/cofres/del/{recompensa_id}
    defaults: { _controller: akira.sladmin.controller:cofres_del }