gray_ficha_home:
    path: /ficha/new
    defaults: { _controller: gray.ficha.controller:handle }
    
gray_ficha_store:    
    path: /ficha/store
    defaults: { _controller: gray.ficha.controller:store }

gray_ficha_view:    
    path: /ficha/{user_id}
    defaults: { _controller: gray.ficha.controller:view }

gray_ficha_delete:
  path: /ficha/delete/{user_id}
  defaults: { _controller: gray.ficha.controller:delete }

gray_ficha_viewMod:    
    path: /ficha/mod/{user_id}
    defaults: { _controller: gray.ficha.controller:viewMod }

gray_ficha_storeMod:    
    path: /ficha/storeMod/{user_id}
    defaults: { _controller: gray.ficha.controller:storeMod }

gray_ficha_buyHab:    
    path: /ficha/hab/{user_id}
    defaults: { _controller: gray.ficha.controller:buyHab }

gray_ficha_lvlUp:    
    path: /ficha/lvlup/{user_id}
    defaults: { _controller: gray.ficha.controller:lvlUp }
    
gray_ficha_nextLvl:
    path: /ficha/nextlvl/{user_id}
    defaults: { _controller: gray.ficha.controller:nextLvl }
    
gray_ficha_sellItem:
    path: /ficha/sellItem/{user_id}
    defaults: { _controller: gray.ficha.controller:sellItem }
    
gray_ficha_saveItem:
    path: /ficha/saveItem/{user_id}
    defaults: { _controller: gray.ficha.controller:saveItem }
    
gray_ficha_buyTec:
    path: /ficha/tec/{user_id}
    defaults: { _controller: gray.ficha.controller:buyTec }
    
gray_ficha_removeTecMod:
    path: /ficha/removeTec/{user_id}
    defaults: { _controller: gray.ficha.controller:removeTecMod }
    
gray_ficha_enable:
    path: /ficha/enable/{user_id}
    defaults: { _controller: gray.ficha.controller:enable }
    
gray_ficha_disable:
    path: /ficha/disable/{user_id}
    defaults: { _controller: gray.ficha.controller:disable }