gray_ficha_home:
    path: /ficha/new
    defaults: { _controller: gray.ficha.controller:handle }
    
gray_ficha_store:    
    path: /ficha/store
    defaults: { _controller: gray.ficha.controller:store }

gray_ficha_view:    
    path: /ficha/{user_id}
    defaults: { _controller: gray.ficha.controller:view }

gray_ficha_delete:
  path: /ficha/delete/{user_id}
  defaults: { _controller: gray.ficha.controller:delete }

gray_ficha_viewMod:    
    path: /ficha/mod/{user_id}
    defaults: { _controller: gray.ficha.controller:viewMod }

gray_ficha_storeMod:    
    path: /ficha/storeMod/{user_id}
    defaults: { _controller: gray.ficha.controller:storeMod }

gray_ficha_buyHab:    
    path: /ficha/hab/{user_id}
    defaults: { _controller: gray.ficha.controller:buyHab }

gray_ficha_lvlUp:    
    path: /ficha/lvlup/{user_id}
    defaults: { _controller: gray.ficha.controller:lvlUp }
    
gray_ficha_nextLvl:
    path: /ficha/nextlvl/{user_id}
    defaults: { _controller: gray.ficha.controller:nextLvl }