services:
    gray.ficha.controller:
        class: gray\ficha\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'