services:
    gray.tecnicas.controller:
        class: gray\tecnicas\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'
