services:
    akira.habilidades.controller:
        class: akira\habilidades\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@auth'